version: '3'

services:
  frontend:
    build: ./frontend
    command: yarn serve
    ports:
      - "8080:8080"
    volumes:
      - .:/frontend
    depends_on:
      - backend
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/backend